/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedAtividadesRouteImport } from './routes/_authenticated/atividades'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedContatosRouteImport } from './routes/_authenticated/contatos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedForecastRouteImport } from './routes/_authenticated/forecast'
import { Route as AuthenticatedIaComercialRouteImport } from './routes/_authenticated/ia-comercial'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedPropostasRouteImport } from './routes/_authenticated/propostas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedReunioesRouteImport } from './routes/_authenticated/reunioes'

const AuthenticatedAtividadesRoute = AuthenticatedAtividadesRouteImport.update({
  id: '/_authenticated/atividades',
  path: '/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/_authenticated/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedContatosRoute = AuthenticatedContatosRouteImport.update({
  id: '/_authenticated/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/_authenticated/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedForecastRoute = AuthenticatedForecastRouteImport.update({
  id: '/_authenticated/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIaComercialRoute =
  AuthenticatedIaComercialRouteImport.update({
    id: '/_authenticated/ia-comercial',
    path: '/ia-comercial',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/_authenticated/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPropostasRoute = AuthenticatedPropostasRouteImport.update({
  id: '/_authenticated/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/_authenticated/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReunioesRoute = AuthenticatedReunioesRouteImport.update({
  id: '/_authenticated/reunioes',
  path: '/reunioes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/ia-comercial': typeof AuthenticatedIaComercialRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/propostas': typeof AuthenticatedPropostasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/reunioes': typeof AuthenticatedReunioesRoute
}
export interface FileRoutesByTo {
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/ia-comercial': typeof AuthenticatedIaComercialRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/propostas': typeof AuthenticatedPropostasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/reunioes': typeof AuthenticatedReunioesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/atividades': typeof AuthenticatedAtividadesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contatos': typeof AuthenticatedContatosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/forecast': typeof AuthenticatedForecastRoute
  '/_authenticated/ia-comercial': typeof AuthenticatedIaComercialRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/propostas': typeof AuthenticatedPropostasRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/reunioes': typeof AuthenticatedReunioesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/atividades'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/empresas'
    | '/forecast'
    | '/ia-comercial'
    | '/pipeline'
    | '/propostas'
    | '/relatorios'
    | '/reunioes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/atividades'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/empresas'
    | '/forecast'
    | '/ia-comercial'
    | '/pipeline'
    | '/propostas'
    | '/relatorios'
    | '/reunioes'
  id:
    | '__root__'
    | '/_authenticated/atividades'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contatos'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresas'
    | '/_authenticated/forecast'
    | '/_authenticated/ia-comercial'
    | '/_authenticated/pipeline'
    | '/_authenticated/propostas'
    | '/_authenticated/relatorios'
    | '/_authenticated/reunioes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAtividadesRoute: typeof AuthenticatedAtividadesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContatosRoute: typeof AuthenticatedContatosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedForecastRoute: typeof AuthenticatedForecastRoute
  AuthenticatedIaComercialRoute: typeof AuthenticatedIaComercialRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedPropostasRoute: typeof AuthenticatedPropostasRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedReunioesRoute: typeof AuthenticatedReunioesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/atividades': {
      id: '/_authenticated/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AuthenticatedAtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contatos': {
      id: '/_authenticated/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AuthenticatedContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/forecast': {
      id: '/_authenticated/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AuthenticatedForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ia-comercial': {
      id: '/_authenticated/ia-comercial'
      path: '/ia-comercial'
      fullPath: '/ia-comercial'
      preLoaderRoute: typeof AuthenticatedIaComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/propostas': {
      id: '/_authenticated/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof AuthenticatedPropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reunioes': {
      id: '/_authenticated/reunioes'
      path: '/reunioes'
      fullPath: '/reunioes'
      preLoaderRoute: typeof AuthenticatedReunioesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAtividadesRoute: AuthenticatedAtividadesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContatosRoute: AuthenticatedContatosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedForecastRoute: AuthenticatedForecastRoute,
  AuthenticatedIaComercialRoute: AuthenticatedIaComercialRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedPropostasRoute: AuthenticatedPropostasRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedReunioesRoute: AuthenticatedReunioesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
